config/routes.rb
Spree::Core::Engine.routes.draw do

  # Add your extension routes here

  namespace :admin do
    resources :stickers do
      member do
        post :clone
      end
    end

    resources :templates do
      member do
        post :clone
      end
    end
    delete 'templates/:template_id/template_frames/:id', to: "template_frames#destroy", as: :template_frame

    resources :filters do
      member do
        post :clone
      end
    end

    resources :backgrounds do
      member do
        post :clone
      end
    end

    resources :products do 
      member do 
        post :get_taxons
      end
    end

    delete '/colors/:id', to: "colors#destroy", as: :color
  end
  resources :products do
    resources :personalize_products, only: [:new, :create, :edit, :update]
    get :get_product_variant
    get :save_gallery_photo
    get '/images/:id/download', to: "products#download", as: :download_image
  end
  resources :photo_galleries, only: [:show]
end

app/views/spree/admin/images/_add_associated_pictures.html.erb
<%= render partial: 'associated_pictures', collection: @product.product_pictures, as: :picture %>
<%= render partial: 'product_associated_background', locals: { image: @product.product_background }  if @product.product_background.present? %>
<%= render partial: 'product_associated_gallery_images', collection: @product.gallery_uploaded_images, as: :gallery_image %>
<%= render partial: 'product_associated_stickers', collection: @product.product_stickers, as: :sticker %>

app/views/spree/admin/images/_associated_pictures.html.erb
<% if picture.product_image.present? %>
  <tr id="<%= spree_dom_id picture %>" data-hook="images_row">

    <td>
      <% if can?(:update_positions, Spree::ProductPicture) %>
        <span class="handle"></span>
      <% end %>
    </td>

    <td>
      <span class="modal-image-trigger" data-toggle="modal" data-target="#modal-image-<%= picture.id %>">
        <%= render 'spree/admin/shared/product_images', image: picture, size: :mini %>
      </span>
      <%= render(
        "spree/admin/shared/modal",
        target: "modal-image-#{picture.id}",
        content: %{
          <div class='align-center'>
            #{image_tag(picture.product_image.url(:original))}
          </div>
        }.html_safe
      ) %>
    </td>

    <td>
      <%= fields_for picture do |f| %>
        <%= f.text_field :id, value: '' %>
      <% end %>
    </td>

    <td class="actions">
      <%= link_to_with_icon 'download', t('spree.actions.download'), product_download_image_url(@product, picture, tablename: "product_pictures", fieldname: "product_image"), no_text: true %>
    </td>
  </tr>
<% end %>

app/views/spree/admin/images/_links_for_images.html.erb
<td class="actions">
  <% if !@product.is_personalize_product? %>
    <% if can?(:update, image) %>
      <%= link_to_with_icon 'check', t('spree.actions.save'), api_variant_image_path(@product, image), no_text: true, data: {action: 'save'} %>

      <%= link_to_with_icon 'cancel', t('spree.actions.cancel'), nil, no_text: true, data: {action: 'cancel'} %>

      <%= link_to_with_icon 'edit', t('spree.actions.edit'), edit_admin_product_image_path(@product, image), no_text: true, data: {action: 'edit'} %>
    <% end %>

    <% if can?(:destroy, image) %>
      <%= link_to_delete image, { url: admin_product_image_url(@product, image), no_text: true } %>
    <% end %>
  <% else %>
    <%= link_to_with_icon 'download', t('spree.actions.download'), product_download_image_path(@product, image, tablename: "images", fieldname: "attachment"), no_text: true, data: {action: 'download'} %>
  <% end %>
</td>

app/views/spree/admin/images/_product_associated_background.html.erb
<!-- For background image -->
<% if image.background_image.present? %>
  <tr id="<%= spree_dom_id image %>" data-hook="images_row">

    <td>
      <% if can?(:update_positions, Spree::ProductBackground) %>
        <span class="handle"></span>
      <% end %>
    </td>

    <td>
      <span class="modal-image-trigger" data-toggle="modal" data-target="#modal-image-<%= image.id %>">
        <%= render 'spree/admin/shared/background', background: image, size: :mini %>
      </span>
      <%= render(
        "spree/admin/shared/modal",
        target: "modal-image-#{image.id}",
        content: %{
          <div class='align-center'>
            #{image_tag(image.background_image.url(:original))}
          </div>
        }.html_safe
      ) %>
    </td>

    <td>
      <%= fields_for image do |f| %>
        <%= f.text_field :id, value: '' %>
      <% end %>
    </td>

    <td class="actions">
      <%= link_to_with_icon 'download', t('spree.actions.download'), product_download_image_url(@product, image, tablename: "product_background", fieldname: "background_image"), no_text: true, data: {action: 'edit'} %>
    </td>
  </tr>
<% end %>

<!-- For frames -->
<% product_frames = @product.template.template_frames %>

<% unless image.product_frame_id.nil? %>
  <% template_frame = product_frames.find image.product_frame_id %>
  <tr id="<%= spree_dom_id template_frame %>" data-hook="images_row">

    <td>
      <% if can?(:update_positions, Spree::ProductBackground) %>
        <span class="handle"></span>
      <% end %>
    </td>

    <td>
      <span class="modal-image-trigger" data-toggle="modal" data-target="#modal-image-<%= template_frame.id %>">
        <% size ||= :mini %>
        <% if template_frame && template_frame.frame_image? %>
          <%= image_tag template_frame.frame_image(:mini) %>
        <% else %>
          <span class="image-placeholder <%= size %>"></span>
        <% end %>
      </span>
      <%= render(
        "spree/admin/shared/modal",
        target: "modal-image-#{template_frame.id}",
        content: %{
          <div class='align-center'>
            #{image_tag(template_frame.frame_image.url(:original))}
          </div>
        }.html_safe
      ) %>
    </td>

    <td>
      <%= fields_for image do |f| %>
        <%= f.text_field :id, value: '' %>
      <% end %>
    </td>

    <td class="actions">
      <%= link_to_with_icon 'download', t('spree.actions.download'), product_download_image_url(@product, template_frame, tablename: "template.template_frames", fieldname: "frame_image"), no_text: true %>
    </td>
  </tr>
<% end %>

app/views/spree/admin/images/_product_associated_gallery_images.html.erb
<% product_id = gallery_image.uploaded_photo_id %>
<% uploaded_product = Spree::Product.find product_id %>
<% uploaded_product_image = uploaded_product.display_image %>

<tr data-hook="images_row">
  <td>
    <% if can?(:update_positions, Spree::GalleryUploadedImage) %>
      <span class="handle"></span>
    <% end %>
  </td>

  <td>
    <span class="modal-image-trigger" data-toggle="modal" data-target="#modal-image-<%= product_id %>">
      <%= render 'spree/admin/shared/gallery_images', image: uploaded_product_image, size: :mini %>
    </span>
    <%= render(
      "spree/admin/shared/modal",
      target: "modal-image-#{product_id}",
      content: %{
        <div class='align-center'>
          #{image_tag(uploaded_product_image.attachment.url(:original))}
        </div>
      }.html_safe
    ) %>
  </td>

  <td>
    <%= fields_for uploaded_product_image do |f| %>
      <%= f.text_field :id, value: '' %>
    <% end %>
  </td>

  <td class="actions">
    <%= link_to_with_icon 'download', t('spree.actions.download'), product_download_image_url(uploaded_product, uploaded_product_image, tablename: "images", fieldname: "attachment"), no_text: true %>
  </td>
</tr>

app/views/spree/admin/images/_product_associated_stickers.html.erb
<% product_sticker = Spree::Sticker.find sticker.sticker_id %>
<tr id="<%= spree_dom_id sticker %>" data-hook="images_row">

  <td>
    <% if can?(:update_positions, Spree::ProductSticker) %>
      <span class="handle"></span>
    <% end %>
  </td>

  <td>
    <span class="modal-image-trigger sticker-small-img" data-toggle="modal" data-target="#modal-sticker-<%= product_sticker.id %>">
      <%= render 'spree/admin/shared/product_stickers', sticker: product_sticker, size: :mini %>
    </span>
    <%= render(
      "spree/admin/shared/modal",
      target: "modal-sticker-#{product_sticker.id}",
      content: %{
        <div class='align-center'>
          #{image_tag(product_sticker.image.url(:original))}
        </div>
      }.html_safe
    ) %>
  </td>

  <td>
    <%= fields_for sticker do |f| %>
      <%= f.text_field :id, value: '' %>
    <% end %>
  </td>

  <td class="actions">
    <%= link_to_with_icon 'download', t('spree.actions.download'), 
      product_download_image_url(@product, sticker.sticker_id, tablename: "product_stickers", fieldname: "image"), no_text: true %>
  </td>
</tr>

app/views/spree/admin/images/index.html.erb
<%= render partial: 'spree/admin/shared/product_tabs', locals: {current: 'Images'} %>

<% admin_breadcrumb(plural_resource_name(Spree::Image)) %>

<% if !@product.is_personalize_product? %>
  <% content_for :page_actions do %>
    <% if can?(:create, Spree::Image) %>
      <li><%= link_to_with_icon('plus', t('spree.new_image'), new_admin_product_image_url(@product), id: 'new_image_link', class: 'button') %></li>
    <% end %>
  <% end %>

  <div id="new_image" class="hidden">
    <%= render 'new', product: @product, image: Spree::Image.new(viewable: @product) %>
  </div>

  <fieldset class="no-border-bottom">
    <legend align="center"><%= t(".upload_images") %></legend>

    <div id="upload-zone">
      <%= form_for [:admin, @product, Spree::Image.new],
          html: { multipart: true, id: 'upload-form' } do |f| %>
        <label class="upload">
          <i class="fa fa-5x fa-cloud-upload"></i>
          <p>
            <span class="button"><%= t(".choose_files") %></span>
          </p>
          <p>
            <%= t(".drag_and_drop") %>
          </p>

          <%= f.file_field :attachment, multiple: '', class: 'hidden' %>
          <%= f.hidden_field :viewable_id, value: @product.master.id %>
        </label>
      <% end %>
    </div>

    <div id="progress-zone" class="row"></div>
  </fieldset>
<% end %>

<% no_images = @product.images.empty? && @product.variant_images.empty? %>

<table class="index sortable inline-editable-table <%= 'hidden' if no_images %>" id="images-table" data-hook="images_table" data-sortable-link="<%= update_positions_admin_product_images_url(@product) %>">
  <colgroup>
    <col style="width: 5%">
    <col style="width: 10%">
    <% if @product.has_variants? %>
      <col style="width: 40%">
    <% end %>
    <col style="width: 30%">
    <col style="width: 15%">
  </colgroup>

  <thead>
    <tr data-hook="images_header">
      <th></th>
      <th><%= t('spree.thumbnail') %></th>
      <% if @product.has_variants? %>
        <th><%= Spree::Variant.model_name.human %></th>
      <% end %>
      <th><%= Spree::Image.human_attribute_name(:alt) %></th>
      <th class="actions"></th>
    </tr>
  </thead>

  <tbody>
    <%= render partial: 'image_row', collection: @product.variant_images, as: :image %>
  </tbody>
</table>

<% if no_images %>
  <div class="no-objects-found">
    <%= t('spree.no_images_found') %>.
  </div>
<% end %>