config/routes.rb
Spree::Core::Engine.routes.draw do

  # Add your extension routes here

  namespace :admin do
    resources :stickers do
      member do
        post :clone
      end
    end

    resources :templates do
      member do
        post :clone
      end
    end
    delete 'templates/:template_id/template_frames/:id', to: "template_frames#destroy", as: :template_frame

    resources :filters do
      member do
        post :clone
      end
    end

    resources :backgrounds do
      member do
        post :clone
      end
    end

    resources :products do 
      member do 
        post :get_taxons
      end
    end

    delete '/colors/:id', to: "colors#destroy", as: :color
  end
  resources :products do
    resources :personalize_products, only: [:new, :create, :edit, :update]
    get :get_product_variant
    get :save_gallery_photo
    get '/images/:id/download', to: "products#download", as: :download_image
  end
  resources :photo_galleries, only: [:show]
end

app/views/spree/admin/templates/_add_fields_permission.html.erb
<label><%= t('spree.template.added_permission') %></label>
<div class="flexibility-check">
  <%= field_container f.object, :flexibility_for_text do %>
    <%= hidden_field_tag :flexibility_for_text, false  %>
    <%= f.check_box :flexibility_for_text, {data: {effect: 'flexibility_for_text'}}, true %>
    <%= f.label :flexibility_for_text, t('spree.template.add_text') %>
    <%= error_message_on f.object, :flexibility_for_text %>
  <% end %>

  <%= field_container f.object, :flexibility_for_background do %>
    <%= hidden_field_tag :flexibility_for_background, false  %>
    <%= f.check_box :flexibility_for_background, {data: {effect: 'flexibility_for_background'}}, true %>
    <%= f.label :flexibility_for_background, t('spree.template.change_background') %>
    <%= error_message_on f.object, :flexibility_for_background %>
  <% end %>

  <%= field_container f.object, :flexibility_for_sticker do %>
    <%= hidden_field_tag :flexibility_for_sticker, false  %>
    <%= f.check_box :flexibility_for_sticker, {data: {effect: 'flexibility_for_sticker'}}, true %>
    <%= f.label :flexibility_for_sticker, t('spree.template.add_sticker') %>
    <%= error_message_on f.object, :flexibility_for_sticker %>
  <% end %>
</div>

app/views/spree/admin/templates/_add_image_fields.html.erb
<div class="tab-pane fade col-md-12" id="layer-<%= img_number %>">
  <div class="layer-settings layer-settings-admin" data-layer="layer-<%= img_number %>">
    <div class="row">
      <div class="col-md-6">
        <div class="form-group">
          <%= field_container f.object, :img_width do %>
            <%= f.label :width, class: 'required' %>
            <%= f.number_field :img_width, data: {effect: 'width'} %>
            <%= error_message_on f.object, :img_width %>
          <% end %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <%= field_container f.object, :img_height do %>
            <%= f.label :height, class: 'required' %>
            <%= f.number_field :img_height, data: {effect: 'height'} %>
            <%= error_message_on f.object, :img_height %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <div class="form-group">
          <%= field_container f.object, :position_x do %>
            <%= f.label :position_x %>
            <%= f.number_field :position_x, data: {effect: 'positionX'} %>
            <%= error_message_on f.object, :position_x %>
          <% end %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <%= field_container f.object, :position_y do %>
            <%= f.label :position_y %>
            <%= f.number_field :position_y, data: {effect: 'positionY'} %>
            <%= error_message_on f.object, :position_y %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="form-group">
          <%= field_container f.object, :border_radius do %>
            <%= f.label :border_radius do %>
              <%= t(:'spree.template.border_radius') %><span class="valueShow "></span>
            <% end %>
            <%= f.range_field :border_radius, data: {effect: 'bradius'}, min: '0', max: (@template.width + @template.height)/2, value: (f.object.border_radius.nil? ? 0 : f.object.border_radius) %>
            <%= error_message_on f.object, :border_radius %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="form-group">
          <%= field_container f.object, :rotate do %>
            <%= f.label :rotate do %>
              <%= t(:'spree.template.rotate') %><span class="valueShow "></span>
            <% end %>
            <%= f.range_field :rotate, data: {effect: 'rotate'}, min: '0', max: '360', value: (f.object.rotate.nil? ? 0 : f.object.rotate) %>
            <%= error_message_on f.object, :rotate %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/spree/admin/templates/_add_template_texts.html.erb
<div class="tab-pane fade col-md-12" id="layer-text-<%= text_number %>">
  <div class="layer-settings layer-settings-admin" data-layer="layer-text-<%= text_number %>">
    <div class="row">
      <div class="col-md-12">
        <div class="form-group">
          <%= field_container f.object, :width do %>
            <%= f.label :width, class: 'required' %>
            <%= f.number_field :width, data: {style: 'width'} %>
            <%= error_message_on f.object, :width %>
          <% end %>
        </div>
      </div>

      <div class="col-md-12">
        <div class="form-group">
          <%= field_container f.object, :height do %>
            <%= f.label :height, class: 'required' %>
            <%= f.number_field :height, data: {style: 'height'} %>
            <%= error_message_on f.object, :height %>
          <% end %>
        </div>
      </div>

      <div class="col-md-12">
        <div class="form-group">
          <%= field_container f.object, :position_x do %>
            <%= f.label :position_x %>
            <%= f.number_field :position_x, data: {style: 'positionX'} %>
            <%= error_message_on f.object, :position_x %>
          <% end %>
        </div>
      </div>

      <div class="col-md-12">
        <div class="form-group">
          <%= field_container f.object, :position_y do %>
            <%= f.label :position_y %>
            <%= f.number_field :position_y, data: {style: 'positionY'} %>
            <%= error_message_on f.object, :position_y %>
          <% end %>
        </div>
      </div>

      <div class="col-md-12">
        <div class="form-group">
          <%= field_container f.object, :rotate do %>
            <%= f.label :rotate do %>
              <%= t(:'spree.personalize_product.rotate') %>
              <span class="valueShow "></span>
            <% end %>
            <%= f.range_field :rotate, data: {style: 'rotate'}, min: '-360', max: '360', value: (f.object.rotate.nil? ? 0 : f.object.rotate) %>
            <%= error_message_on f.object, :rotate %>
          <% end %>
        </div>
      </div>

      <div class="col-md-12">
        <div class="form-group">
          <%= field_container f.object, :font_size do %>
            <%= f.label :font_size do %>
              <%= t(:'spree.personalize_product.font_size') %>
              <span class="valueShow"></span>
            <% end %>
            <%= f.range_field :font_size, data: {style: 'font_size'}, min: '50', max: '400', value: (f.object.font_size.nil? ? 76 : f.object.font_size) %>
            <%= error_message_on f.object, :font_size %>
          <% end %>
        </div>
      </div>

      <div class="col-md-12">
        <div class="form-group">
          <%= field_container f.object, :font_color do %>
            <%= f.label :font_color do %>
              <%= t(:'spree.personalize_product.font_color') %>
            <% end %>
            <ul>
              <li class="width-100" data-textstyle="color">
                <label class="color-picker">
                  <%= f.text_field :font_color, data: {style: 'fontcolor'}, class: 'colorpicker-element' %>
                </label>
                <i class="fa fa-eyedropper"></i>
                <span style="background-color: #333" class="color"></span>
              </li>
            </ul>
            <%= error_message_on f.object, :font_color %>
          <% end %>
        </div>
      </div>

      <div class="col-md-12">
        <div class="form-group">
          <%= field_container f.object, :font_family do %>
            <%= f.label :font_family do %>
              <%= t(:'spree.personalize_product.font_family') %>
            <% end %>
            <%= f.text_field :font_family, class: 'font', data: {style: 'font-style'} %>
            <%= error_message_on f.object, :font_family %>
          <% end %>
        </div>
      </div>

      <div class="col-md-12">
        <div class="form-group">
          <%= field_container f.object, :text_content do %>
            <%= f.hidden_field :text_content, data: {style: 'text-content'} %>
            <%= error_message_on f.object, :text_content %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/spree/admin/templates/_form.html.erb
<div class="form-group" data-hook="admin_template_form_name">
  <%= f.field_container :name do %>
    <%= f.label :template_name, class: 'required' %>
    <%= f.text_field :name, class: 'fullwidth title', required: true %>
    <%= f.error_message_on :name %>
  <% end %>
</div>

<div class="form-group" data-hook="admin_template_form_description">
  <%= f.field_container :description do %>
    <%= f.label :template_description %>
    <%= f.text_area :description, class: 'fullwidth title form-control', rows: "3" %>
    <%= f.error_message_on :description %>
  <% end %>
</div>

<div class="row">
  <div class="col-md-6">
    <div class="form-group" data-hook="admin_template_form_width">
      <%= f.field_container :width do %>
        <%= f.label :template_width , class: 'required' %>
        <%= f.number_field :width, data: {range: 'width'}, required: true, class: 'range-field' %>
        <%= f.error_message_on :width %>
      <% end %>
    </div>
  </div>
  <div class="col-md-6">
    <div class="form-group" data-hook="admin_template_form_height">
      <%= f.field_container :height do %>
        <%= f.label :template_height, class: 'required' %>
        <%= f.number_field :height, data: {range: 'height'}, required: true, class: 'range-field' %>
        <%= f.error_message_on :height %>
      <% end %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="form-group" data-hook="admin_template_form_edges">
      <%= f.field_container :resolution do %>
        <%= f.label :template_resolution do %>
          Template Resolution<span class="valueShow"></span>
        <% end %>
        <%= f.range_field :resolution, data: {range: 'resolution'}, min: '0', max: '300' %>
        <%= f.error_message_on :resolution %>
      <% end %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="form-group" data-hook="admin_template_form_edges">
      <%= f.field_container :edges do %>
        <%= f.label :template_rounded_edges do %>
          Template Rounded Edges<span class="valueShow"></span>
        <% end %>
        <% max_edge = @template.present? ? @template.width : '400' %>
        <%= f.range_field :edges, data: {range: 'radius'}, min: '0', max: max_edge %>
        <%= f.error_message_on :edges %>
      <% end %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="form-group hide-margin" data-hook="admin_template_form_number_of_images">
      <%= f.field_container :background do %>
        <%= f.label :background %>
        <label class="radio-inline">
          <%= f.radio_button :background, 'background_image' %><%= I18n.t('spree.template.background_image') %>
        </label>
        <label class="radio-inline">
          <%= f.radio_button :background, 'background_color' %><%= I18n.t('spree.template.background_color') %>
        </label>
      <% end %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <div class="form-group background-image-block" data-hook="admin_template_form_background_image">
      <%= f.field_container :background_image do %>
        <label>
          <% if f.object.background_image.nil? %>
            <%= f.file_field :background_image, data: {picture: 'background_image'}, class: 'field-border fullwidth form-control' %>
          <% else %>
            <%= f.file_field :background_image, data: {picture: ' background_image', url: f.object.background_image.url(:original) }, class: 'field-border fullwidth form-control' %>
            <%= f.check_box :remove_background_image, class: 'd-none' %>
          <% end %>
          <%= f.error_message_on :background_image %>
        </label>
      <% end %>
    </div>
    <div class="form-group" data-hook="admin_template_form_background_color">
      <%= f.field_container :background_color do %>
        <ul>
          <li class="width-100" data-textstyle="color">
            <label class="color-picker">
              <%= f.text_field :background_color, data: {color: 'background_color'}, class: 'colorpicker-element-bg' %>
            </label>
            <i class="fa fa-eyedropper"></i>
            <span style="background-color: #333" class="color"></span>
          </li>
        </ul>
        <%= f.error_message_on :background_color %>
      <% end %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <table  class="form-group frame-block" data-hook="admin_template_form_frame">
      <thead>
        <tr>
          <th><%= f.label :template_frames, t('spree.template.template_frame'), class: 'frame-label' %></th>
          <th colspan="2" class="text-right"><%= link_to_add_fields t('spree.template.add_frames'), 'tbody#template_frames', class: 'button spree_add_frame_fields' %></th>
        </tr>
      </thead>
      <tbody id="template_frames" class="add-template-frames">
        <% count = 0 %>
        <%= f.fields_for :template_frames do |template_frame_form| %>
          <% count += 1 %>
          <%= render partial: 'template_frames', locals: { ff: template_frame_form, count: count, f: f }%>
        <% end %>
      </tbody>
    </table >
  </div>
</div>

<div class="row">
  <div class="col-md-6">
    <div class="form-group" data-hook="admin_template_form_number_of_images">
      <%= f.field_container :number_of_images do %>
        <%= f.label :add_images %>
        <%= f.number_field :number_of_images, class: 'fullwidth title form-control', min: '0', max: '20' %>
        <%= f.error_message_on :number_of_images %>
      <% end %>
    </div>
  </div>
  <div class="col-md-6">
    <div class="form-group" data-hook="admin_template_form_number_of_images">
      <%= f.field_container :number_of_text_boxes do %>
        <%= f.label :add_texts %>
        <%= f.number_field :number_of_text_boxes, class: 'fullwidth title form-control', min: '0', max: '20' %>
        <%= f.error_message_on :number_of_text_boxes %>
      <% end %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="form-group" data-hook="admin_template_fields_permission">
      <%= f.fields_for :template_fields_permission do |ff| %>
        <%= render partial: 'add_fields_permission', locals: { f: ff } %>
      <% end %>
    </div>
  </div>
</div>

app/views/spree/admin/templates/_preview_shape.html.erb
<% images_number_range = images_range(@template) %>
<% if number_of_images?(@template) %>
  <% images_number_range.each do |img_number| %>
    <div class="preview-inner-img" data-layer="layer-<%= img_number %>"></div>
  <% end %>
<% end %>

<% text_boxes_range = textboxes_range(@template) %>
<% if number_of_text_boxes?(@template) %>
  <% text_boxes_range.each do |text_number| %>
    <div class="preview-inner-img preview-inner-text" data-layer="layer-text-<%= text_number %>"></div>
  <% end %>
<% end %>

app/views/spree/admin/templates/_template_frames.html.erb
<tr class="template-frames fields" data-hook="template_frame" >
  <td class="align-items-middle" style="width:300px"><%= ff.file_field :frame_image, data: {picture: 'frame', layer: "frame-layer-#{count}"}, class: 'field-border fullwidth form-control custom-fle-inpt', multipart: true %>
    <span class="file-input-span"><%= t('spree.template.select_file') %></span>
  </td>
  <% if ff.object.persisted? %>
    <td class="align-items-middle" style="width:300px"><%= image_tag ff.object.frame_image.url(:small), class: 'frame-img-input' %></td>
    <td class="actions align-items-middle" style="width:100px"><%= link_to_delete_frame ff.object, no_text: true, class: 'delete-frame spree_remove_fields', url: admin_template_frame_path(f.object, ff.object), method: :delete, remote: :true %></td>
  <% else %>
    <td></td>
    <td class="actions align-items-middle" style="width:50px"><%= link_to_remove_fields t('spree.actions.remove'), ff, no_text: true %></td>
  <% end %>
</tr>

app/views/spree/admin/templates/_template_layers_tabs.html.erb
<div class="form-content template-layers">
  <div class="row">
    <div class="col-md-12">
      <div class="form-group">
        <ul class="nav nav-tabs custom-nav-tabs" id="interest_tabs">
          <% if number_of_images?(@template) %>
            <label><%= t('spree.template.template_layers') %></label>
            <li><a href="#images-layer" data-toggle="tab" class="layer-tabs"><%= f.label :images_layer, t('spree.template.image_layers') %></a></li>
          <% end %>
          <% if number_of_text_boxes?(@template) %>
            <li><a href="#texts-layer" data-toggle="tab" class="layer-tabs"><%= f.label :texts_layer %></a></li>
          <% end %>
        </ul>
        
        <div class="tab-content">
          <% if number_of_images?(@template) %>
            <div id="images-layer" class="tab-pane">
              <ul class="nav nav-tabs custom-nav-tabs" id="images_layer_tabs layer-setting-admin">
                <% (@template.template_images).each_with_index do |template_image, img_number| %>
                  <li>
                    <%= link_to "Image Placeholder #{img_number+1}",
                      "#layer-#{img_number+1}", {class: 'layer-tabs', data: { toggle: 'tab', value: "layer-#{img_number+1}" }} %>
                  </li>
                <% end %>
              </ul>
            </div>
          <% end %>
          
          <% if number_of_text_boxes?(@template) %>
            <div id="texts-layer" class="tab-pane">
              <ul class="nav nav-tabs custom-nav-tabs" id="texts_layer_tabs layer-setting-admin">
                <% (@template.template_texts).each_with_index do |template_text, text_number| %>
                  <li>
                    <%= link_to "Text Placeholder #{text_number+1}",
                      "#layer-text-#{text_number+1}", {data: { toggle: 'tab', value: "layer-text-#{text_number+1}" }, class: 'txt-lyr layer-tabs' } %>
                  </li>
                <% end %>
              </ul>
            </div>
          <% end %>
        </div>

        <div class="tab-content">
          <% if @template.number_of_images.present? %>
            <% (@template.template_images).each_with_index do |template_image, img_number| %>
              <%= f.fields_for :template_images, template_image do |template_image| %>
                <%= render partial: 'add_image_fields', locals: { f: template_image, img_number: img_number+1 } %>
              <% end %>
            <% end %> 
          <% end %>
        </div>

        <div class="tab-content">
          <% if @template.number_of_text_boxes.present? %>
            <% (@template.template_texts).each_with_index do |template_text, text_number| %>
              <%= f.fields_for :template_texts, template_text do |template_text| %>
                <%= render partial: 'add_template_texts', locals: { f: template_text, text_number: text_number+1 } %>
              <% end %>
            <% end %> 
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/spree/admin/templates/edit.html.erb
<% admin_layout "full-width" %>

<% content_for :page_actions do %>
  <% if can?(:create, Spree::Template) %>
    <li id="new_template_link">
      <%= button_link_to t('spree.new_template'), new_object_url, { id: 'admin_new_template' } %>
    </li>
  <% end %>
<% end %>

<%= render partial: 'spree/shared/error_messages', locals: { target: @template } %>

<% admin_breadcrumb(t('spree.template_details')) %>

<div data-hook="admin_template_form_fields">
  <main class="gxp-admin">
    <div class="row">
      <div class="container col-12 text-left">
        <%= form_for [:admin, @template] do |f| %>
          <fieldset class="no-border-top no-border-bottom sticky-container">
            <div class="zoom-inout-scale" data-zoom-scale="<%= (500.to_f / @template.width.to_f).round(1) %>" data-zoom-change="0.05">
              <button class="btn" data-zoom="negative">
                <i class="fa fa-minus"></i>
              </button>
              <button class="btn" data-zoom="positive">
                <i class="fa fa-plus"></i>
              </button>
              <div class="current-size">
                <%= t('spree.scale.label') %>: <%= t('spree.scale.original') %>
              </div>
            </div>
            <div class="row">
              <div class="col-md-8"><!-- sticky-static -->
                <div class="overflow-container">
                  <div class="template-preview">
                    <h2><%= t(:'spree.template.template_preview') %></h2>
                    <div class="frame-list">
                      <% template_frames = @template.template_frames %>
                      <% if template_frames.present? %>
                        <% i = 0 %>
                        <% template_frames.each do |frame|%>
                        <% i += 1 %>
                         <% if frame.frame_image.present? %>
                            <div class="frame-images" data-layer="frame-layer-<%= i %>">
                              <%= image_tag frame.frame_image.url(:original)  %>
                            </div>
                          <% end %>
                        <% end %>
                      <% end %>
                    </div>
                    <div class="scale-parent">
                      <div class="preview-shape">
                        <div id="frame-preview">
                          <%= image_tag template_frames.first.frame_image.url(:original) if template_frames.present? %>
                        </div>
                          <!-- preview shape of images and text -->
                          <%= render partial: 'preview_shape' %>
                        </div>
                      </div>
                    </div>
                </div>
              </div>
              <div class="col-md-4">
                <div class="form-content form-content-scroll">
                  <%= render partial: 'form', locals: { f: f } %>
                  <%= render partial: 'template_layers_tabs', locals: { f: f } %>
                </div>
              </div>
            </div>
          </fieldset>

          <% if can?(:update, @template) %>
            <fieldset class="no-border-top">
              <%= render partial: 'spree/admin/shared/edit_resource_links' %>
            </fieldset>
          <% end %>
        <% end %>
      </div>
    </div>
  </main>
</div>

app/views/spree/admin/templates/index.html.erb
<% admin_layout "full-width" %>

<% admin_breadcrumb(plural_resource_name(Spree::Template)) %>

<% content_for :page_actions do %>
  <li id="new_template_link">
    <%= button_link_to Spree.t(:new_template), new_admin_template_path, { :id => 'new_admin_template' } %>
  </li>
<% end if can?(:create, Spree::Template) %>

<% content_for :table_filter_title do %>
  <%= Spree.t(:search) %>
<% end %>

<% content_for :table_filter do %>
  <div data-hook="admin_templates_sidebar">
    <%= search_form_for [:admin, @search] do |f| %>
        <%- locals = {f: f} %>
        <div class="row" data-hook="admin_templates_index_search" >
          <div class="col-12">
            <div class="field">
              <%= f.label :name_cont, Spree::Template.human_attribute_name(:name) %>
              <%= f.text_field :name_cont, size: 15 %>
            </div>
          </div>
        </div>

        <div class="actions filter-actions" data-hook="admin_templates_index_search_buttons">
          <%= button t('spree.search') %>
        </div>
    <% end %>
  </div>
<% end %>

<div id="new_template_wrapper" data-hook></div>

<%= paginate @collection, theme: "solidus_admin" %>

<% if @collection.any? %>
  <table class="index" id="listing_templates">
    <thead>
      <tr data-hook="admin_templates_index_headers">
        <th><%= sort_link @search, :name, Spree::Template.human_attribute_name(:name), { default_order: "desc" }, {title: 'admin_templates_listing_name_title'} %></th>
        <th><%= Spree::Template.human_attribute_name(:description) %></th>
        <th><%= Spree::Template.human_attribute_name(:width) %></th>
        <th><%= Spree::Template.human_attribute_name(:height) %></th>
        <th><%= Spree::Template.human_attribute_name(:edges) %></th>
        <th><%= Spree::Template.human_attribute_name(:total_images) %></th>
        <th><%= Spree::Template.human_attribute_name(:total_textboxes) %></th>
        <th><%= Spree::Template.human_attribute_name(:background) %>
        <th data-hook="admin_templates_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @collection.each do |template| %>
          <tr <%== "style='color: red;'" if template.deleted? %> id="<%= spree_dom_id template %>" data-hook="admin_templates_index_rows">
            <td><%= link_to template.try(:name), edit_admin_template_path(template) %></td>
            <td><%= template.description %></td>
            <td><%= template.width %></td>
            <td><%= template.height %></td>
            <td><%= template.edges %></td>
            <td class="text-center"><%= template.number_of_images %></td>
            <td class="text-center"><%= template.number_of_text_boxes %></td>
            <% if template.background_color.present? %>
              <td class="temp-bg" style="background-color: <%= template.background_color %>;">
              </td>
            <% elsif template.background_image.present? %>
              <td class="temp-bg"><%= image_tag template.background_image.url(:original) %></td>
            <% else %>
              <td></td>
            <% end %>
            <td class="actions" data-hook="admin_templates_index_row_actions">
              <%= link_to_edit template, no_text: true, class: 'edit' if can?(:edit, template) && !template.deleted? %>
              &nbsp;
              <%= link_to_clone template, no_text: true, class: 'clone' if can?(:clone, template) %>
              &nbsp;
              <% if template.products.present? %>
                <%= link_to_delete(template, options={no_text: true, confirm: t('spree.template.associated_with_product')}) if can?(:delete, template) && !template.deleted? %>
              <% else %>
                <%= link_to_delete template, no_text: true if can?(:delete, template) && !template.deleted? %>
              <% end %>
            </td>
          </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="no-objects-found">
    <%= render 'spree/admin/shared/no_objects_found',
                  resource: Spree::Template,
                  new_resource_url: new_object_url %>
  </div>
<% end %>

<%= paginate @collection, theme: "solidus_admin" %>

app/views/spree/admin/templates/new.html.erb
<% admin_breadcrumb link_to(plural_resource_name(Spree::Template), spree.admin_templates_path) %>

<% admin_breadcrumb t('spree.new_template') %>

<%= render partial: 'spree/shared/error_messages', locals: { target: @template } %>

<div data-hook="admin_template_form_fields">
  <main class="gxp-admin">
    <div class="">
      <div class="container">
        <%= form_for [:admin, @template], method: :post, url: admin_templates_path do |f| %>
          <fieldset data-hook="new_template" class="no-border-top no-border-bottom sticky-container">
            <div class="zoom-inout-scale" data-zoom-scale="0.8" data-zoom-change="0.01">
              <button class="btn" data-zoom="negative">
                <i class="fa fa-minus"></i>
              </button>
              <button class="btn" data-zoom="positive">
                <i class="fa fa-plus"></i>
              </button>
              <div class="current-size">
                <%= t('spree.scale.label') %>: <%= t('spree.scale.original') %>
              </div>
            </div>
            <legend align="center"><%= t('spree.new_template') %></legend>
            <div class="row">
              <div class="col-md-7"> <!-- sticky-static -->
                <div class="overflow-container">
                  <div class="template-preview">
                    <h2><%= t(:'spree.template.template_preview') %></h2>
                    <div class="frame-list"></div>
                    <div class="preview-shape">
                      <div class="frame-preview"></div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-md-5">
                <div class="form-content form-content-scroll">
                  <%= render partial: 'form', locals: { f: f } %>
                </div>
              </div>
            </div>
          </fieldset>
          <fieldset class="no-border-top">
            <%= render partial: 'spree/admin/shared/new_resource_links' %>
          </fieldset>
        <% end %>
      </div>
    </div>
  </main>
</div>