config/routes.rb
Spree::Core::Engine.routes.draw do

  # Add your extension routes here

  namespace :admin do
    resources :stickers do
      member do
        post :clone
      end
    end

    resources :templates do
      member do
        post :clone
      end
    end
    delete 'templates/:template_id/template_frames/:id', to: "template_frames#destroy", as: :template_frame

    resources :filters do
      member do
        post :clone
      end
    end

    resources :backgrounds do
      member do
        post :clone
      end
    end

    resources :products do 
      member do 
        post :get_taxons
      end
    end

    delete '/colors/:id', to: "colors#destroy", as: :color
  end
  resources :products do
    resources :personalize_products, only: [:new, :create, :edit, :update]
    get :get_product_variant
    get :save_gallery_photo
    get '/images/:id/download', to: "products#download", as: :download_image
  end
  resources :photo_galleries, only: [:show]
end

app/models/spree/filter.rb
require 'discard'

module Spree
  class Filter < Spree::Base
    acts_as_paranoid
    include Spree::ParanoiaDeprecations

    include Discard::Model
    self.discard_column = :deleted_at

    validates_presence_of :name

    has_many :colors, inverse_of: :filter, class_name: 'Spree::Color', dependent: :destroy
    accepts_nested_attributes_for :colors, allow_destroy: true, reject_if: proc {|att| att['color_code'].blank?}

    after_discard do
      colors.discard_all
    end

    def deleted?
      !!deleted_at
    end

    def duplicate
      duplicator = FilterDuplicator.new(self)
      duplicator.duplicate
    end

    def slug_candidates
      [
        :name
      ]
    end
  end
end

app/controllers/spree/admin/filters_controller.rb
module Spree
  module Admin
    class FiltersController < ResourceController

      helper_method :clone_object_url

      def index
        session[:return_to] = request.url
        respond_with(@collection)
      end

      def show
        redirect_to action: :edit
      end

      def update
        if @object.update_attributes(permitted_resource_params)
          flash[:success] = flash_message_for(@object, :successfully_updated)
          respond_with(@object) do |format|
            format.html { redirect_to spree.edit_admin_filter_url }
            format.js   { render layout: false }
          end
        else
          # Stops people submitting blank slugs, causing errors when they try to
          # update the filter again
          @filter.slug = @filter.slug_was if @filter.slug.blank?
          respond_with(@object)
        end
      end

      def clone
        @new = @filter.duplicate

        if @new.save
          flash[:success] = t('spree.notice_messages.filter_cloned')
          redirect_to edit_admin_filter_url(@new)
        else
          flash[:error] = t('spree.notice_messages.filter_not_cloned', error: @new.errors.full_messages)
          redirect_to admin_filters_url
        end
      end

      def destroy
        @filter = Spree::Filter.find(params[:id])
        @filter.discard

        flash[:success] = t('spree.notice_messages.filter_deleted')

        respond_with(@filter) do |format|
          format.html { redirect_to collection_url }
          format.js { render_js_for_destroy }
        end
      end

      private
        def find_resource
          Spree::Filter.with_deleted.find(params[:id])
        end

        def collection
          return @collection if @collection
          params[:q] ||= {}
          params[:q][:s] ||= "name asc"
          # @search needs to be defined as this is passed to search_form_for
          @search = super.ransack(params[:q])
          @collection = @search.result.
                order(id: :asc).
                page(params[:page]).per(params[:per_page])
        end

        def build_color
          @filter.colors.build
        end

        def clone_object_url(resource)
          clone_admin_filter_url resource
        end
    end
  end
end

app/helpers/spree/admin/filters_helper.rb
module Spree::Admin::FiltersHelper
  def build_color_array(filter)
    color_arr = []
    filter.colors.each do |color|
      color_arr.push(color.try(:color_code))
    end

    color_arr.reverse
  end
end

app/views/spree/admin/filters/_color_fields.html.erb
<%= field_container color.object, :color_code, {} do %>
  <tr class="color_code fields" id="spree_<%= dom_id(color.object) %>"  data-hook="color_code">
    <td class="color_code">
      <div class="input-group input-color-grp">
        <%= color.text_field :color_code, class: 'filter-color form-control', data: { 'color-pick': "transparent" }, placeholder: "Select Color" %>
        <span class="input-group-addon"></span>
        <%= error_message_on color.object, :color_code, 'aria-describedby': "basic-addon1" %>
      </div>
    </td>
    <td class="actions"><%= link_to_remove_fields t('spree.actions.remove'), color, no_text: true %></td>
  </tr>
<% end %>

app/views/spree/admin/filters/_form.html.erb
<div data-hook="admin_filter_form_fields">
  <div class="row">
    <div class="left col-5" data-hook="admin_filter_form_left">
      <div data-hook="admin_filter_form_image">
        <h2><%= t('spree.filter.preview') %></h2>
        <div class="preview-filter">
          <div class="filter-div"></div>
          <%= image_tag "spree/backend/filter-bg.jpg" %>
        </div>
        <div class="preview-filter-png"></div>
      </div>
    </div>

    <div class="left col-7">
      <div data-hook="admin_filter_form_name">
        <%= f.field_container :name do %>
          <%= f.label :name, class: 'required' %>
          <%= f.text_field :name, class: 'fullwidth title', required: true %>
          <%= f.error_message_on :name %>
        <% end %>
      </div>

      <div data-hook="admin_filter_form_color_code">
        <% f.object.colors.build if f.object.colors.blank? %>
        <table class="index sortable" data-hook data-sortable-link="<%= update_values_positions_admin_option_types_url %>">
          <colgroup>
            <col width="70%">
            <col width="30%">
          </colgroup>
          <thead data-hook="option_header">
            <tr>
              <th><%= Spree::Color.human_attribute_name(:color_code) %></th>
              <th class="actions">
                <span id="new_add_color_codes" data-hook >
                  <%= link_to_add_fields t('spree.filter.add_color_code'), "tbody#color_codes", class: 'button' %>
                </span>
              </th>
            </tr>
          </thead>
          <tbody id="color_codes">
            <%= f.fields_for :colors do |color| %>
              <%= render partial: 'color_fields', locals: { color: color } %>
            <% end %>
          </tbody>
        </table>
      </div>

      <div class="form-group">
        <label><input type="checkbox" id="gradientCheck"> <%= t('spree.filter.gradient') %></label>
      </div>

      <div class="gradientbox">
        <div class="gradientStrip mb-4">
          <div class="gradient-strip-color"></div>
        </div>
      </div>

    </div>
  </div>

app/views/spree/admin/filters/edit.html.erb
<% content_for :page_actions do %>
  <% if can?(:create, Spree::Filter) %>
    <li id="new_filter_link">
      <%= button_link_to t('spree.new_filter'), new_object_url, { id: 'admin_new_filter' } %>
    </li>
  <% end %>
<% end %>

<%= render partial: 'spree/shared/error_messages', locals: { target: @filter } %>

<% admin_breadcrumb(t('spree.filter_details')) %>

<%= form_for [:admin, @filter], html: { multipart: true } do |f| %>
  <fieldset class="no-border-top">
    <%= render partial: 'form', locals: { f: f } %>
    <% if can?(:update, @filter) %>
      <%= render partial: 'spree/admin/shared/edit_resource_links' %>
    <% end %>
  </fieldset>
<% end %>

app/views/spree/admin/filters/index.html.erb
<% admin_layout "full-width" %>

<% admin_breadcrumb(plural_resource_name(Spree::Filter)) %>

<% content_for :page_actions do %>
  <li id="new_filter_link">
    <%= button_link_to Spree.t(:new_filter), new_admin_filter_path, { :id => 'new_admin_filter' } %>
  </li>
<% end if can?(:create, Spree::Filter) %>

<% content_for :table_filter do %>
  <div data-hook="admin_filters_sidebar">
    <%= search_form_for [:admin, @search] do |f| %>
        <%- locals = {f: f} %>
        <div class="row" data-hook="admin_filters_index_search" >
          <div class="col-12">
            <div class="field">
              <%= f.label :name_cont, Spree::Filter.human_attribute_name(:name) %>
              <%= f.text_field :name_cont, size: 15 %>
            </div>
          </div>
        </div>

        <div class="actions filter-actions" data-hook="admin_filters_index_search_buttons">
          <%= button t('spree.search') %>
        </div>
    <% end %>
  </div>
<% end %>

<div id="new_filter_wrapper" data-hook></div>

<%= paginate @collection, theme: "solidus_admin" %>

<% if @collection.any? %>
  <table class="index" id="listing_filters">
    <colgroup>
      
    </colgroup>
    <thead>
      <tr data-hook="admin_filters_index_headers">
        <th><%= sort_link @search, :name, Spree::Filter.human_attribute_name(:name), { default_order: "desc" }, {title: 'admin_filters_listing_name_title'} %></th>
        <th><%= Spree::Filter.human_attribute_name(:color_code) %></th>
        <th data-hook="admin_filters_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @collection.each do |filter| %>
          <tr <%== "style='color: red;'" if filter.deleted? %> id="<%= spree_dom_id filter %>" data-hook="admin_filters_index_rows">
            <td class="align-left"><%= link_to filter.try(:name), edit_admin_filter_path(filter) %></td>
            <td>
              <div class="gradientStrip mb-4 color-gradient-arr" data-color-arr="<%= build_color_array(filter) %>">
                <div class="gradient-strip-color"></div>
              </div>
            </td>
            <td class="actions" data-hook="admin_filters_index_row_actions">
              <%= link_to_edit filter, no_text: true, class: 'edit' if can?(:edit, filter) && !filter.deleted? %>
              &nbsp;
              <%= link_to_clone filter, no_text: true, class: 'clone' if can?(:clone, filter) %>
              &nbsp;
              <%= link_to_delete filter, no_text: true if can?(:delete, filter) && !filter.deleted? %>
            </td>
          </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="no-objects-found">
    <%= render 'spree/admin/shared/no_objects_found',
                  resource: Spree::Filter,
                  new_resource_url: new_object_url %>
  </div>
<% end %>

<%= paginate @collection, theme: "solidus_admin" %>

app/views/spree/admin/filters/new.html.erb
<% admin_breadcrumb link_to(plural_resource_name(Spree::Filter), spree.admin_stickers_path) %>

<% admin_breadcrumb t('spree.new_filter') %>
  
<%= render partial: 'spree/shared/error_messages', locals: { target: @filter } %>

<%= form_for [:admin, @filter], method: :post, url: admin_filters_path, html: { multipart: true } do |f| %>
  <fieldset data-hook="new_sticker">
    <legend align="center"><%= t('spree.new_filter') %></legend>

    <%= render partial: 'form', locals: { f: f } %>

    <%= render partial: 'spree/admin/shared/new_resource_links' %>
  </fieldset>
<% end %>