config/routes.rb
Spree::Core::Engine.routes.draw do

  # Add your extension routes here

  namespace :admin do
    resources :stickers do
      member do
        post :clone
      end
    end

    resources :templates do
      member do
        post :clone
      end
    end
    delete 'templates/:template_id/template_frames/:id', to: "template_frames#destroy", as: :template_frame

    resources :filters do
      member do
        post :clone
      end
    end

    resources :backgrounds do
      member do
        post :clone
      end
    end

    resources :products do 
      member do 
        post :get_taxons
      end
    end

    delete '/colors/:id', to: "colors#destroy", as: :color
  end
  resources :products do
    resources :personalize_products, only: [:new, :create, :edit, :update]
    get :get_product_variant
    get :save_gallery_photo
    get '/images/:id/download', to: "products#download", as: :download_image
  end
  resources :photo_galleries, only: [:show]
end

app/models/spree/sticker.rb
require 'discard'

module Spree
  class Sticker < Spree::Base
    acts_as_paranoid
    include Spree::ParanoiaDeprecations

    include Discard::Model
    self.discard_column = :deleted_at

    validate :no_attachment_errors

    validates_presence_of :name, :image

    has_attached_file :image,
               styles: { mini: '48x48>', small: '100x100>', product: '240x240>', large: '600x600>' },
                default_style: :sticker,
                url: '/spree/stickers/:id/:style/:basename.:extension',
                path: ':rails_root/public/spree/stickers/:id/:style/:basename.:extension',
                convert_options: { all: '-strip -auto-orient -colorspace sRGB' }
    validates_attachment :image,
      presence: true,
      content_type: { content_type: %w(image/png), message: 'only allow png' }

    validates_with AttachmentSizeValidator, attributes: :image, less_than: 3.megabytes

    validate :check_dimensions


    def check_dimensions
      temp_file = image.queued_for_write[:original]
      unless temp_file.nil?
        dimensions = Paperclip::Geometry.from_file(temp_file)
        width = dimensions.width
        height = dimensions.height
        if width < 2000 && height < 2000
          errors['image'] << I18n.t('spree.sticker.image.dimension_error')
        # elsif width != height
        #   errors['image'] << I18n.t('spree.sticker.image.box_error')
        end
      end
    end

    # if there are errors from the plugin, then add a more meaningful message
    def no_attachment_errors
      unless image.errors.empty?
        # uncomment this to get rid of the less-than-useful interim messages
        # errors.clear
        errors.add :image, "Paperclip returned errors for file '#{image_file_name}' - check ImageMagick installation or image source file."
        false
      end
    end

    # Try building a slug based on the following fields in increasing order of specificity.
    def slug_candidates
      [
        :name
      ]
    end

    def deleted?
      !!deleted_at
    end

    # Creates a new sticker with the same attributes.
    #
    # @return [Spree::Sticker] the duplicate
    def duplicate
      duplicator = StickerDuplicator.new(self)
      duplicator.duplicate
    end

  end
end

app/controllers/spree/admin/stickers_controller.rb
module Spree
  module Admin
    class StickersController < ResourceController

      helper_method :clone_object_url

      def index
        session[:return_to] = request.url
        respond_with(@collection)
      end

      def show
        redirect_to action: :edit
      end

      def update
        if @object.update_attributes(permitted_resource_params)
          flash[:success] = flash_message_for(@object, :successfully_updated)
          respond_with(@object) do |format|
            format.html { redirect_to spree.edit_admin_sticker_url }
            format.js   { render layout: false }
          end
        else
          # Stops people submitting blank slugs, causing errors when they try to
          # update the sticker again
          @sticker.slug = @sticker.slug_was if @sticker.slug.blank?
          respond_with(@object)
        end
      end

      def destroy
        @sticker = Spree::Sticker.find(params[:id])
        @sticker.discard

        flash[:success] = t('spree.notice_messages.sticker_deleted')

        respond_with(@sticker) do |format|
          format.html { redirect_to collection_url }
          format.js { render_js_for_destroy }
        end
      end

      def clone
        @new = @sticker.duplicate

        if @new.save
          flash[:success] = t('spree.notice_messages.sticker_cloned')
          redirect_to edit_admin_sticker_url(@new)
        else
          flash[:error] = t('spree.notice_messages.sticker_not_cloned', error: @new.errors.full_messages)
          redirect_to admin_stickers_url
        end
      end

      private
        def find_resource
          Spree::Sticker.with_deleted.find(params[:id])
        end

        def collection
          return @collection if @collection
          params[:q] ||= {}
          params[:q][:s] ||= "name asc"
          # @search needs to be defined as this is passed to search_form_for
          @search = super.ransack(params[:q])
          @collection = @search.result.
                order(id: :asc).
                page(params[:page]).per(params[:per_page])
        end

        def clone_object_url(resource)
          clone_admin_sticker_url resource
        end

    end
  end
end

app/helpers/spree/admin/stickers_helper.rb
module Spree::Admin::StickersHelper
end

app/views/spree/admin/stickers/_form.html.erb
<div data-hook="admin_sticker_form_fields">

  <div class="row">

    <div class="left col-6" data-hook="admin_sticker_form_left">
      <div data-hook="admin_sticker_form_name">
        <%= f.field_container :name do %>
          <%= f.label :name, class: 'required' %>
          <%= f.text_field :name, class: 'fullwidth title', required: true %>
          <%= f.error_message_on :name %>
        <% end %>
      </div>
    </div>

    <div class="left col-6" data-hook="admin_sticker_form_right">
      <div data-hook="admin_sticker_form_slug">
        <%= f.field_container :slug do %>
          <%= f.label :slug, class: ('required' if !f.object.new_record?) %>
          <%= f.text_field :slug, class: 'fullwidth title', required: !f.object.new_record?, disabled: f.object.new_record? %>
          <%= f.error_message_on :slug %>
        <% end %>
      </div>
    </div>

    <div class="left col-12" data-hook="admin_sticker_image">
      <div data-hook="admin_sticker_form_image">
        <%= f.field_container :image do %>
          <%= f.label :image %>
          <%= f.file_field :image, class: 'fullwidth' %>
          <%= f.error_message_on :image %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/spree/admin/stickers/edit.html.erb
<% content_for :page_actions do %>
  <% if can?(:create, Spree::Sticker) %>
    <li id="new_sticker_link">
      <%= button_link_to t('spree.new_sticker'), new_object_url, { id: 'admin_new_sticker' } %>
    </li>
  <% end %>
<% end %>

<%= render partial: 'spree/shared/error_messages', locals: { target: @sticker } %>

<% admin_breadcrumb(t('spree.sticker_details')) %>

<%= form_for [:admin, @sticker], html: { multipart: true } do |f| %>
  <fieldset class="no-border-top">
    <%= render partial: 'form', locals: { f: f } %>
    <% if can?(:update, @sticker) %>
      <%= render partial: 'spree/admin/shared/edit_resource_links' %>
    <% end %>
  </fieldset>
<% end %>

app/views/spree/admin/stickers/index.html.erb
<% admin_layout "full-width" %>

<% admin_breadcrumb(plural_resource_name(Spree::Sticker)) %>

<% content_for :page_actions do %>
  <li id="new_sticker_link">
    <%= button_link_to Spree.t(:new_sticker), new_admin_sticker_path, { :id => 'new_admin_sticker' } %>
  </li>
<% end if can?(:create, Spree::Sticker) %>

<% content_for :table_filter_title do %>
  <%= Spree.t(:search) %>
<% end %>

<% content_for :table_filter do %>
  <div data-hook="admin_stickers_sidebar">
    <%= search_form_for [:admin, @search] do |f| %>
        <%- locals = {f: f} %>
        <div class="row" data-hook="admin_stickers_index_search" >
          <div class="col-12">
            <div class="field">
              <%= f.label :name_cont, Spree::Sticker.human_attribute_name(:name) %>
              <%= f.text_field :name_cont, size: 15 %>
            </div>
          </div>
        </div>

        <div class="actions filter-actions" data-hook="admin_stickers_index_search_buttons">
          <%= button t('spree.search') %>
        </div>
    <% end %>
  </div>
<% end %>

<div id="new_sticker_wrapper" data-hook></div>

<%= paginate @collection, theme: "solidus_admin" %>

<% if @collection.any? %>
  <table class="index" id="listing_stickers">
    <colgroup>
       <col style="width: 20%;">
       <col style="width: 30%;">
       <col style="width: 30%;">
       <col style="width: 20%;">
    </colgroup>
    <thead>
      <tr data-hook="admin_stickers_index_headers">
        <th><%= Spree::Sticker.human_attribute_name(:image) %></th>
        <th><%= sort_link @search, :name, Spree::Sticker.human_attribute_name(:name), { default_order: "desc" }, {title: 'admin_stickers_listing_name_title'} %></th>
        <th><%= Spree::Sticker.human_attribute_name(:slug) %></th>
        <th data-hook="admin_stickers_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @collection.each do |sticker| %>
          <tr <%== "style='color: red;'" if sticker.deleted? %> id="<%= spree_dom_id sticker %>" data-hook="admin_stickers_index_rows">
            <td class="align-center"><%= image_tag sticker.image.url(:original), class: 'sticker-img' %></td>
            <td><%= link_to sticker.try(:name), edit_admin_sticker_path(sticker) %></td>
            <td><%= sticker.slug %></td>
            <td class="actions" data-hook="admin_stickers_index_row_actions">
              <%= link_to_edit sticker, no_text: true, class: 'edit' if can?(:edit, sticker) && !sticker.deleted? %>
              &nbsp;
              <%= link_to_clone sticker, no_text: true, class: 'clone' if can?(:clone, sticker) %>
              &nbsp;
              <%= link_to_delete sticker, no_text: true if can?(:delete, sticker) && !sticker.deleted? %>
            </td>
          </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="no-objects-found">
    <%= render 'spree/admin/shared/no_objects_found',
                  resource: Spree::Sticker,
                  new_resource_url: new_object_url %>
  </div>
<% end %>

<%= paginate @collection, theme: "solidus_admin" %>

app/views/spree/admin/stickers/new.html.erb
<% admin_breadcrumb link_to(plural_resource_name(Spree::Sticker), spree.admin_stickers_path) %>

<% admin_breadcrumb t('spree.new_sticker') %>

<%= render partial: 'spree/shared/error_messages', locals: { target: @sticker } %>

<%= form_for [:admin, @sticker], method: :post, url: admin_stickers_path, html: { multipart: true } do |f| %>
  <fieldset data-hook="new_sticker">
    <legend align="center"><%= t('spree.new_sticker') %></legend>

    <%= render partial: 'form', locals: { f: f } %>

    <%= render partial: 'spree/admin/shared/new_resource_links' %>
  </fieldset>
<% end %>